[package]
name = "pom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
crossterm = "0.27.0"
indicatif = "0.17.7"
termion = "2.0.1"
